(display "Hello, World!\n")
(display #t)
(display "\n")
(display #f)
(display "\n")
(display 42)
(display "\n")
(display 3.14159)
(display "\n")
(display 'fib)
(display "\n")
(display '(1 2 3))
(display "\n")
